# House price prediction project
1. Problem definition:
   * Goal: predict the sales price for each house. For each Id in the test set, you must predict the value of the SalePrice variable. 

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_df = pd.read_csv("train.csv")

In [4]:
data_df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [5]:
data_df = pd.read_csv("train.csv", index_col = "Id")

In [6]:
data_df

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                      
1             60       RL         65.0     8450   Pave   NaN      Reg   
2             20       RL         80.0     9600   Pave   NaN      Reg   
3             60       RL         68.0    11250   Pave   NaN      IR1   
4             70       RL         60.0     9550   Pave   NaN      IR1   
5             60       RL         84.0    14260   Pave   NaN      IR1   
...          ...      ...          ...      ...    ...   ...      ...   
1456          60       RL         62.0     7917   Pave   NaN      Reg   
1457          20       RL         85.0    13175   Pave   NaN      Reg   
1458          70       RL         66.0     9042   Pave   NaN      Reg   
1459          20       RL         68.0     9717   Pave   NaN      Reg   
1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence MiscFeature  \
Id                                    ...                                      
1            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
2            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
3            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
4            Lvl    AllPub    Corner  ...        0    NaN    NaN         NaN   
5            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
...          ...       ...       ...  ...      ...    ...    ...         ...   
1456         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1457         Lvl    AllPub    Inside  ...        0    NaN  MnPrv         NaN   
1458         Lvl    AllPub    Inside  ...        0    NaN  GdPrv        Shed   
1459         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1460         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   

     MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                               
1          0      2    2008        WD         Normal     208500  
2          0      5    2007        WD         Normal     181500  
3          0      9    2008        WD         Normal     223500  
4          0      2    2006        WD        Abnorml     140000  
5          0     12    2008        WD         Normal     250000  
...      ...    ...     ...       ...            ...        ...  
1456       0      8    2007        WD         Normal     175000  
1457       0      2    2010        WD         Normal     210000  
1458    2500      5    2010        WD         Normal     266500  
1459       0      4    2010        WD         Normal     142125  
1460       0      6    2008        WD         Normal     147500  

[1460 rows x 80 columns]

In [7]:
data_df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

### 2. Feature selection
* Choose important features to train ML model (Feature Engineering)

In [8]:
features = ["LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF", "FullBath", "BedroomAbvGr", "TotRmsAbvGrd"]

### 3. Splitting the dataset
* x: data[feature]
* y: target variable SalePrice

In [9]:
x = data_df[features]

In [10]:
x

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                     
1        8450       2003       856       854         2             3   
2        9600       1976      1262         0         2             3   
3       11250       2001       920       866         2             3   
4        9550       1915       961       756         1             3   
5       14260       2000      1145      1053         2             4   
...       ...        ...       ...       ...       ...           ...   
1456     7917       1999       953       694         2             3   
1457    13175       1978      2073         0         2             3   
1458     9042       1941      1188      1152         2             4   
1459     9717       1950      1078         0         1             2   
1460     9937       1965      1256         0         1             3   

      TotRmsAbvGrd  
Id                  
1                8  
2                6  
3                6  
4                7  
5                9  
...            ...  
1456             7  
1457             7  
1458             9  
1459             5  
1460             6  

[1460 rows x 7 columns]

In [11]:
y = data_df["SalePrice"]

In [12]:
y

Id
1       208500
2       181500
3       223500
4       140000
5       250000
         ...  
1456    175000
1457    210000
1458    266500
1459    142125
1460    147500
Name: SalePrice, Length: 1460, dtype: int64

### Splitting dataset into training set and test set
## To avoid the overfitting
# x, y -> x_train, y_train, x_test, y_test

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=0)
#random_state: do not change the state anytime run the func

In [14]:
x_train.shape

(1168, 7)

In [15]:
x_test.shape

(292, 7)

### 4.Training the ML model

#### 1. Using decision tree

In [16]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(random_state=1)

In [17]:
# Fit training data into model
dt_model.fit(x_train, y_train)

DecisionTreeRegressor(random_state=1)

In [18]:
y_predicts = dt_model.predict(x_test.head())

In [19]:
y_predicts

array([335000., 140200., 119000., 207500., 112000.])

In [20]:
pd.DataFrame({'y': y_test.head(), 'y_predicts': y_predicts})

y  y_predicts
Id                     
530  200624    335000.0
492  133000    140200.0
460  110000    119000.0
280  192000    207500.0
656   88000    112000.0

#### The diff is still quite mass

In [21]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(x_train, y_train)

RandomForestRegressor(random_state=1)

In [22]:
y_rf_pred = rf_model.predict(x_test)

In [23]:
y_rf_pred

array([271690.        , 155039.        , 122024.        , 188915.        ,
        91147.        ,  88533.2       , 240518.24      , 126286.        ,
       624269.12      , 174312.25333333, 209138.46      , 147714.5       ,
       233088.25      , 123139.5       , 140503.75      , 139187.        ,
       232538.3       , 134260.        , 145952.24      , 130562.05      ,
       129304.53      , 147179.68333333, 112355.46      , 183320.22      ,
       153926.5       , 182853.57      , 176891.        ,  86320.        ,
       308784.98      , 112746.        , 141734.5       , 190094.        ,
       124460.65      , 280081.94      , 317780.6       , 179756.65      ,
       218512.64      , 118609.16      , 224329.28      , 304517.56      ,
       229449.        , 141422.15333333, 186872.35      , 302902.86      ,
       316105.83      , 139820.        , 105783.66      , 127933.25      ,
       165361.5       , 118615.5       , 314806.34      , 145952.75      ,
       168104.74      , 1

In [25]:
pd.DataFrame({'y': y_test, 'y_predicts': y_rf_pred})


y  y_predicts
Id                      
530   200624   271690.00
492   133000   155039.00
460   110000   122024.00
280   192000   188915.00
656    88000    91147.00
...      ...         ...
327   324000   275931.87
441   555000   478954.15
1388  136000   176038.00
1324   82500    78096.00
62    101000    81104.00

[292 rows x 2 columns]

#### 4. Testing the model with an real life data

In [26]:
x_test.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                    
530    32668       1957      2515         0         3             4   
492     9490       1941       958       620         1             3   
460     7015       1950       979       224         1             3   
280    10005       1977      1156       866         2             4   
656     1680       1971       525       567         1             3   

     TotRmsAbvGrd  
Id                 
530             9  
492             5  
460             5  
280             8  
656             6

In [27]:
rf_model.predict([[6478, 1997, 956, 877, 4, 3, 5]])

C:\Users\tuana\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([219513.99])

#### 5. Model evaluation

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
y_rf_pred.shape

In [ ]:
y_test.resize(y_rf_pred.shape)
y_test.astype(int)

In [ ]:
y_rf_pred.astype(int)

In [ ]:
accuracy_score(y_rf_pred, y_test)

In [ ]:
train test validation và grid search CV 