In [2]:
import numpy as np

<h1>Create Numpy Arrays from python lists</h1>

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
[3.14, 2, 1]

[3.14, 2, 1]

In [5]:
np.array([3.14, 4.2, 3])

array([3.14, 4.2 , 3.  ])

In [7]:
#np.array giúp chuyển đổi kiểu dữ liệu
np.array([1,2,3,4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])
type(a2)

numpy.ndarray

In [5]:
#cho biết kích thước của ma trận
a2.shape

(2, 3)

In [13]:
#cho biết số chiều của mảng
a2.ndim

2

In [14]:
a2.dtype #kiẻu dữ liệu của các phần tử trong mảng

dtype('int64')

In [15]:
#tổng các thành phần trong mảng np
a2.size 

6

<h1>Create numpy arrays from Scratch:
zeros, ones, full, arange, linespace</h1>

In [17]:
#tạo một mảng gồm toàn 0, nhấn shift + tab để biết thêm hàm zeros cần thêm gì
np.zeros([2,4], dtype = int)   #.dtype: float64


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
#hàm toàn số 1
np.ones([3,5], dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#Create an array filled with a linear sequence 
#Starting at 0, ending at 20, stepping by 2
#this is similar to the built-in range() func
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#hàm full: tạo np.array theo ý mình muốn
np.full([3,5], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [22]:
#Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

<h1>Hàm Random trong np</h1>

In [24]:
np.random.random([4,4])

array([[0.49402082, 0.20330622, 0.52747904, 0.53947826],
       [0.73902078, 0.79709749, 0.83462526, 0.23134095],
       [0.76027327, 0.08858906, 0.6779517 , 0.76386491],
       [0.56690473, 0.70484074, 0.07422632, 0.61546095]])

In [29]:
np.random.random([4,4])


array([[0.45615033, 0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256, 0.1289263 ]])

In [31]:
#Seed for reproducibility: tính lặp lại trong hàm random
np.random.seed(0)
np.random.random([4,4])   #chạy bao nhiêu lần vẫn ra cùng 1 kết quả

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [32]:
np.random.normal(0,1,[3,3])    #tạo mẫu ngẫu nhiên từ phân phối gauss
#Giá trị đầu tiên là giá trị TB(mean), giá trị thứ 2 là Standard deviation (độ lệch chuẩn)

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [33]:
#random interger: randint(low, high=None, size=None, dtype=int)
np.random.randint(0, 10, [4,5]) #low >= 0, high < 10

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]], dtype=int32)

In [34]:
np.random.rand(4,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

<h1>Array indexing and Slicing </h1>

<h2>One-dimensional subarray</h2>

In [35]:
x1 = np.random.randint(20, size = 6)

In [36]:
x1

array([15, 13, 16, 17,  5,  9], dtype=int32)

In [37]:
x1[4]

np.int32(5)

<h2>Multi-dimensional array </h2>

In [38]:
x2 = np.random.randint(10, size = (3,4))

In [39]:
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]], dtype=int32)

In [40]:
x2[1,2]

np.int32(4)

<h2>Slicing
x [start:stop:step]</h2>

In [41]:
x1

array([15, 13, 16, 17,  5,  9], dtype=int32)

In [44]:
#lấy 3 kí tự đầu trong x1
x1[0:3:1]

array([15, 13, 16], dtype=int32)

<h4>Every 2 steps</h4>

In [45]:
x1[::2]

array([15, 16,  5], dtype=int32)

In [46]:
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]], dtype=int32)

In [47]:
#2 rows, 3 cols
x2[:2, :3]

array([[3, 0, 5],
       [1, 2, 4]], dtype=int32)

In [48]:
x2[:, :2] #tất cả các dòng với 2 cột đầu

array([[3, 0],
       [1, 2],
       [0, 3]], dtype=int32)

<h1>Reshaping arrays & Transpose</h1>

In [51]:
grid =  np.arange(1, 10)
grid.shape

(9,)

In [52]:
grid.reshape([3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
x = np.array([1,2,3])

In [54]:
x.shape

(3,)

In [55]:
x.reshape([1,3])

array([[1, 2, 3]])

In [57]:
x.reshape([1,3]).shape


(1, 3)

<h3>Transpose: convert từ cột thành hàng và hàng thành cột</h3>

In [59]:
x = np.array([[1., 2.], [3., 4.]])

In [60]:
x

array([[1., 2.],
       [3., 4.]])

In [61]:
#Ma trân chuyển vị
x.T

array([[1., 3.],
       [2., 4.]])

<h1>Array concatenation and Splitting 

In [8]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [10]:
np.concatenate((x, y), )

array([1, 2, 3, 3, 2, 1])

In [11]:
grid = np.array([[1,2,3], [4,5,6]])
grid 

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.concatenate((grid, grid))  #axis = 0: default nối theo chiều ngang

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
np.concatenate((grid, grid), axis = 1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [14]:
#vstack: concat theo chiều dọc
x = np.array([1,2,3])
grid = np.array([[9,8,7], 
                 [6,5,4]])

In [15]:
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [16]:
#horizontally stack the arrays: hstack
y = np.array([[99],
              [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

<h3>Splitting of arrays</h3>

In [5]:
x = np.array([1,2,3,99,69,3,2,1])

In [19]:
np.split(x, 4)

[array([1, 2]), array([ 3, 99]), array([69,  3]), array([2, 1])]

In [20]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 69]), array([3, 2, 1])]

In [6]:
x1, x2, x3 = np.split(x, [3,5])

In [22]:
x1

array([1, 2, 3])

In [8]:
x2

array([99, 69])

In [9]:
x3

array([3, 2, 1])

<h1>Broadcasting and Vectorized ops <br>Một tập các quy tắc để áp dụng các hàm nhị phân(eg: addition, subtraction, multiplication, etc) trên những mảng kích thước khác nhau 
</h1>

In [4]:
a = np.arange(3)
a

array([0, 1, 2])

In [5]:
a + 5 #broadcasting 

array([5, 6, 7])

In [6]:
b = np.ones([3,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
a.shape, b.shape

((3,), (3, 3))

In [8]:
a + b #broadcast array a = size array b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [9]:
c = np.arange(3).reshape([3,1])
c

array([[0],
       [1],
       [2]])

In [10]:
a + c #braodcast cả a và c cho thành 1 mtr 3x3

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

<h1>Manipulating & Comparing Arrays</h1>

<h2>Aggregation = Performing the same operation on a number of thing</h2>

In [15]:
list_number = [1,2,3]

In [14]:
ll = np.array(list_number)

In [17]:
ll

array([1, 2, 3])

In [20]:
sum(ll) #python sum
  #np.sum(ll) giúp tính toán nhanh chóng hơn

np.int64(6)

In [25]:
#Create a massive numpy array
massive_array = np.random.random(10000)
massive_array.size #or .shape

10000

In [27]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

597 μs ± 16.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
4.9 μs ± 24.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [29]:
np.mean(massive_array)  #giá trị TB của các phần tử trong massive_array

np.float64(0.49676611545080396)

In [32]:
np.max(massive_array)

np.float64(0.9998834602994575)

In [34]:
np.min(massive_array)

np.float64(0.00010733662493034313)

<h1>Standard Deviation(Độ lệch chuẩn) and Variance(phương sai)</h1>

<h2>Standard Deviation
Standard Deviation is a measure of how spread out numbers are.(đo độ phân tán của dữ liệu)</h2>

In [36]:
dog_height = [600, 470, 170, 430, 300]

In [38]:
np.array(dog_height)

array([600, 470, 170, 430, 300])

In [40]:
np.std(dog_height)

np.float64(147.32277488562318)

In [43]:
np.var(dog_height)

np.float64(21704.0)

In [44]:
np.sqrt(np.var(dog_height)) #std = sqrt(var)

np.float64(147.32277488562318)

<h1>Sorting array</h1>

<h2>np.sort use quick sort algo</h2>

In [48]:
x = np.array([2,1,3,4,7,5])
np.sort(x)

array([1, 2, 3, 4, 5, 7])

In [49]:
# A realted func is argsort, which instead returns the indices of the sorted elements: 
np.argsort(x)

array([1, 0, 2, 3, 5, 4])

<h2>Sort multi-dimesional arrays<br>Sorting along rows and cols using the axis argument </h2>

In [51]:
np.random.seed(42)
MatA = np.random.randint(0, 10, size = (4,6))

In [52]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [53]:
np.sort(MatA, axis = 0)   #Sort theo cols: axis = 0

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

In [54]:
np.sort(MatA, axis = 1)  #Sort theo rows

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

<h1>Linear Algebra</h1>

In [56]:
A = np.array([[1,2,3], 
              [4,5,6],
              [7,8,9]])

In [58]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [59]:
#A(3x3) dot product B(3x2)

In [60]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [62]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [64]:
#B (2x3) dot A (3x3)
B.T #(3x2) dot A(3x3)

array([[6, 4, 2],
       [5, 3, 1]])

In [67]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

<h1>Dot Product Example</h1>

In [85]:
#Number of jars sold 
np.random.seed(0) #random ra same arrays
sales_amount = np.random.randint(20, size = (5,3))


In [70]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [75]:
#Create Weekly_sales DataFrame 
import pandas as pd
weekly_sales = pd.DataFrame(sales_amount, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"], columns = ["Coke", "Fanta", "7UP"])

In [76]:
weekly_sales

Coke  Fanta  7UP
Mon      12     15    0
Tues      3      3    7
Wed       9     19   18
Thurs     4      6   12
Fri       1      6    7

In [87]:
#Create a price array
prices = np.array([10, 8, 12])
prices.shape

(3,)

In [89]:
drink_prices = pd.DataFrame(prices.reshape(1, 3), index = ["Price"], columns = ["Coke", "Fanta", "7UP"])
drink_prices

Coke  Fanta  7UP
Price    10      8   12

In [91]:
weekly_sales.shape, drink_prices.shape

((5, 3), (1, 3))

In [93]:
total_price = weekly_sales @ drink_prices.T

In [94]:
total_price

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [96]:
weekly_sales["Total_price"] = total_price

In [97]:
weekly_sales

Coke  Fanta  7UP  Total_price
Mon      12     15    0          240
Tues      3      3    7          138
Wed       9     19   18          458
Thurs     4      6   12          232
Fri       1      6    7          142